CREATE TABLE EMP_ID (ID NUMBER);

SELECT * FROM EMP_ID;

INSERT INTO EMP_ID
SELECT LEVEL FROM DUAL 
CONNECT BY LEVEL <=10;

DELETE FROM EMP_ID WHERE ID =1;

COMMIT;


-----ALTER TABLE EMP_ID MONITORING;

EXEC DBMS_STATS.FLUSH_DATABASE_MONITORING_INFO;

SELECT *
FROM   USER_TAB_MODIFICATIONS
WHERE  TABLE_NAME = 'EMP_ID';


